CC=gcc

all: lab2-1 lab2-2 lab2-3 lab2-4

lab2-1: lab2-1.c
	$(CC) -o lab2-1 lab2-1.c

lab2-2: lab2-2.c
	$(CC) -o lab2-2 lab2-2.c

lab2-3: lab2-3.c
	$(CC) -o lab2-3 lab2-3.c

lab2-4: lab2-4.c
	$(CC) -o lab2-4 lab2-4.c
